GET http://localhost:5000/products


###

POST http://localhost:5000/products
Content-Type: application/json


{

  "name":"Bag",
  "description":"green color",
  "price":150,
  "quantity":1
}


###

GET http://localhost:5000/products/641993bd1b5edd6a0fcaea0f