
###user
# get all users
GET http://localhost:5000/users

# add user
###
POST http://localhost:5000/users
Content-Type: application/json

{
"email":"Annabelle@cabc.com",
"username":"Anna",
"password":"nBj4o54689"
}

# login
###
POST http://localhost:5000/users/login
Content-Type: application/json


{
"email":"Annaabc.com",
"username":"Anna",
"password":"123456789"
}

###Products
# get all products
GET http://localhost:5000/products


###
# create product
POST http://localhost:5000/products
Content-Type: application/json


{
"name":"Prada Bag",
  "description":"Glod color",
  "price":1020,
  "quantity":1
}


###
# get product by id
GET http://localhost:5000/products/641af9bbf537cf87dc42e3f1


###
# update product by id
PUT http://localhost:5000/products/641af9bbf537cf87dc42e3f1
Content-Type: application/json


{

"description":"White Bag"
}

###
# delete product by id
Delete http://localhost:5000/products/641afa7df537cf87dc42e3fa


###cart
# get users cart

GET http://localhost:5000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWI4YWRmMDNkNGY0MWY3MDllNmUzMSIsImlhdCI6MTY3OTU3NzY2OSwiZXhwIjoxNjc5NjY0MDY5fQ.5bz9ToOLdvHAarjpN85jk41KiTfwEKCWEg8wUCyVHYg


###
# add cart
POST http://localhost:5000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWI4YWRmMDNkNGY0MWY3MDllNmUzMSIsImlhdCI6MTY3OTU3NzY2OSwiZXhwIjoxNjc5NjY0MDY5fQ.5bz9ToOLdvHAarjpN85jk41KiTfwEKCWEg8wUCyVHYg



{
"product":"641af8c47e50a0a2107cb815"
}


###
##remove product from cart

DELETE  http://localhost:5000/cart/641af8c47e50a0a2107cb815
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWI4YWRmMDNkNGY0MWY3MDllNmUzMSIsImlhdCI6MTY3OTU3NzY2OSwiZXhwIjoxNjc5NjY0MDY5fQ.5bz9ToOLdvHAarjpN85jk41KiTfwEKCWEg8wUCyVHYg


###
###checkout
POST http://localhost:5000/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWI4YWRmMDNkNGY0MWY3MDllNmUzMSIsImlhdCI6MTY3OTU3NzY2OSwiZXhwIjoxNjc5NjY0MDY5fQ.5bz9ToOLdvHAarjpN85jk41KiTfwEKCWEg8wUCyVHYg






